<div class="row-fluid">

    <div class="span3">
        <ul class="nav nav-list well">
            <li class="nav-header">Dinâmicas</li>
<li>
    <a href="#">
        VARRENDO O QUE É RUIM
    </a>
</li>
<li>
    <a href="#">
        APRENDENDO A DESCANSAR EM DEUS
    </a>
</li>
<li>
    <a href="#">
        ENXERGANDO O QUE É BOM
    </a>
</li>
<li>
    <a href="#">
        OLHANDO PARA SI PRÓPRIO
    </a>
</li>
<li>
    <a href="#">
        AMAR AO PRÓXIMO COMO A SI MESMO
    </a>
</li>
<li>
    <a href="#">
        RÓTULOS DO MUNDO
    </a>
</li>
<li>
    <a href="#">
        INDIFERENÇA 
    </a>
</li>
<li>
    <a href="#">
        A PALAVRA-CHAVE 
    </a>
</li>
<li>
    <a href="#">
        ENCONTRO DE GRUPOS 
    </a>
</li>
<li>
    <a href="#">
        DINÂMICA DO ROLO DE BARBANTE
    </a>
</li>
<li>
    <a href="#">
        AJUDA MÚTUA
    </a>
</li>
<li>
    <a href="#">
        A LÍNGUA DOS SINAIS
    </a>
</li>
<li>
    <a href="#">
        A PROVA DAS MOEDAS
    </a>
</li>
<li>
    <a href="#">
        A DINÂMICA DO BALÃO
    </a>
</li>
<li>
    <a href="#">
        CESTA DE VERSÍCULOS
    </a>
</li>
<li>
    <a href="#">
        EU NÃO SABIA...
    </a>
</li>
<li>
    <a href="#">
        FAÇA O QUE EU FAÇO
    </a>
</li>
<li>
    <a href="#">
        GOLPE DE VISTA
    </a>
</li>
<li>
    <a href="#">
        INTELIGÊNCIA ARTIFICIAL
    </a>
</li>
<li>
    <a href="#">
        MÍMICA
    </a>
</li>
<li>
    <a href="#">
        NOME E QUALIDADE
    </a>
</li>
<li>
    <a href="#">
        O QUE VOCÊ SALVARIA?
    </a>
</li>
<li>
    <a href="#">
        PASSANDO O CHAPÉU
    </a>
</li>
<li>
    <a href="#">
        PLATAFORMA DE GOVERNO
    </a>
</li>
<li>
    <a href="#">
        PROVA DE DITADO
    </a>
</li>
<li>
    <a href="#">
        PROVA DE EQUILÍBRIO
    </a>
</li>
<li>
    <a href="#">
        QUAL O MELHOR CAMINHO?
    </a>
</li>
<li>
    <a href="#">
        QUEM MAIS FEZ ISSO?
    </a>
</li>
<li>
    <a href="#">
        TEIA DE GENTE
    </a>
</li>
<li>
    <a href="#">
        TEXTO ENIGMÁTICO
    </a>
</li>
<li>
    <a href="#">
        O ENIGMA DO CAIO
    </a>
</li>
<li>
    <a href="#">
        TESTE DE LÓGICA
    </a>
</li>
<li>
    <a href="#">
        RESPOSTA RELÂMPAGO
    </a>
</li>
<li>
    <a href="#">
        DINÂMICA DO NOME
    </a>
</li>
<li>
    <a href="#">
        DINÂMICA DA QUALIDADE
    </a>
</li>
<li>
    <a href="#">
        DINÂMICA "TIRO PELA CULATRA"
    </a>
</li>

          

          
        </ul>
    </div>
    <div class="span9">
        <div class="page-header">
            <h1>Dinâmicas</h1>
        </div> 
    </div>
</div>


