<div class="row-fluid">

    <div class="span3">
        <ul class="nav nav-list well">
          
          <li>
            <a href="http://ibcbh.com.br/imagensDin/editor/file/Lic%CC%A7a%CC%83o%20de%20Ce%CC%81lula_13-07-2012%20WEB.pdf">
              <i class="icon-download-alt"></i>
              A Graça de Deus
            </a>
          </li>
          <li class="divider"></li>
          <li class="nav-header">Cronológicas</li>
          <li>
            <a href="#">
              Julho 2012
            </a>
          </li>
          <li>
            <a href="#">
              Junho 2012
            </a>
          </li>
          <li>
            <a href="#">
              Maio 2012
            </a>
          </li>
          <li>
            <a href="#">
              Abril 2012
            </a>
          </li>
          <li class="nav-header">Séries</li>
          <li>
            <a href="#">
              Único: A Exclusividade de Cristo
            </a>
          </li>
          <li>
            <a href="#">
              Multiplicação
            </a>
          </li>
          <li>
            <a href="#">
              A Bússola: O que norteia sua vida?
            </a>
          </li>
          <li>
            <a href="#">
              Paixão Contagiante
            </a>
          </li>
          
        </ul>
    </div>
    <div class="span9">
        <div class="page-header">
            <h1>Lições de Célula</h1>
        </div> 
    </div>
</div>