<div class="row-fluid">

    <div class="span3">
        <ul class="nav nav-list well">
            <li class="nav-header">Letras</li>
                <li>
                    <a href="#">
                        Nívea Soares
                    </a>
                </li>
                <li>
                    <a href="#">
                        Iadoración
                    </a>
                </li>
                <li>
                    <a href="#">
                        Kleber Lucas
                    </a>
                </li>
                <li>
                    <a href="#">
                        David Quinlan
                    </a>
                </li>
            <li class="nav-header">Cifras</li>
            <li>
                    <a href="#">
                        Nívea Soares
                    </a>
                </li>
                <li>
                    <a href="#">
                        Iadoración
                    </a>
                </li>
                <li>
                    <a href="#">
                        Kleber Lucas
                    </a>
                </li>
                <li>
                    <a href="#">
                        David Quinlan
                    </a>
                </li>
            <li class="nav-header">Video Clipes</li>
            <li class="nav-header">MP3</li>
          

          
        </ul>
    </div>
    <div class="span9">
        <div class="page-header">
            <h1>Louvor</h1>
        </div> 
    </div>
</div>