<div class="row-fluid">
    <div class="span3">
        <ul class="nav nav-list well">
            <li>
            <a href="/configuracoes/perfil">
              <i class="icon-user"></i>
              Perfil
            </a>
          </li>
          <li class="active">
            <a href="/configuracoes/contato">
              <i class="icon-bullhorn"></i>
              Contato
            </a>
          </li>
          <li>
            <a href="/configuracoes/endereco">
              <i class="icon-map-marker"></i>
              Endereço
            </a>
          </li>
          <li>
            <a href="/configuracoes/senha">
              <i class="icon-key"></i>
              Senha
            </a>
          </li>
      </ul>
    </div>

    <div class="span9">
        <div class="page-header">
            <h1>Contato</h1>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <form class="form-horizontal" method="post" action="">
            
                        <div class="control-group">
                            <label class="control-label" for="input01">Telefone</label>
                            <div class="controls">
                                <input type="text" class="input-large" id="input01" name="phone" id="phone" value="<?=$this->phone?>" placeholder="(DDD) 9999-9999">
                            </div><!--/.controls -->
                        </div><!--/.control-group -->

                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Salvar alterações</button>
                            <button class="btn">Cancelar</button>
                        </div>
                </form>
            </div>
        </div>
    </div>
    
</div><!--/.row-fluid -->