<div class="row-fluid">
    <div class="span3">
        <ul class="nav nav-list well">
            <li>
            <a href="/configuracoes/perfil">
              <i class="icon-user"></i>
              Perfil
            </a>
          </li>
          <li>
            <a href="/configuracoes/contato">
              <i class="icon-bullhorn"></i>
              Contato
            </a>
          </li>
          <li>
            <a href="/configuracoes/endereco">
              <i class="icon-map-marker"></i>
              Endereço
            </a>
          </li>
          <li class="active">
            <a href="/configuracoes/senha">
              <i class="icon-key"></i>
              Senha
            </a>
          </li>
      </ul>
    </div>

    <div class="span9">
        <div class="page-header">
            <h1>Senha</h1>
        </div>
        <div class="row-fluid">
            <div class="span12">
                <form class="form-horizontal" action="" method="post">
                        <div class="control-group">
                            <label class="control-label" for="input01">Senha atual</label>
                            <div class="controls">
                                <input type="password" class="input-large" id="input01" name="old_password" id="old_password">
                            </div><!--/.controls -->
                        </div><!--/.control-group -->
                        <div class="control-group">
                            <label class="control-label" for="input01">Nova senha</label>
                            <div class="controls">
                                <input type="password" class="input-large" id="input01" name="new_password" id="new_password" placeholder="mín. 6 caracteres">
                            </div><!--/.controls -->
                        </div><!--/.control-group -->
                        <div class="control-group">
                            <label class="control-label" for="input01">Repita nova senha</label>
                            <div class="controls">
                                <input type="password" class="input-large" id="input01" name="confirm_password" id="confirm_password" placeholder="mín. 6 caracteres">
                            </div><!--/.controls -->
                        </div><!--/.control-group -->
                        <div class="form-actions">
                            <button type="submit" class="btn btn-primary">Salvar alterações</button>
                            <button class="btn">Cancelar</button>
                        </div>
                </form>
            </div>
        </div>
    </div>
    
</div><!--/.row-fluid -->
