<div class="masthead">
        <h3 class="muted">Igreja Batista Central</h3>
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                <li class="active"><a href="#">Células</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=3&IdArea=3">A Igreja</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=4&IdArea=4">Células</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=5&IdArea=5">Ministérios</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=7&IdArea=7">CCM</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=6&IdArea=6">Missões</a></li>
                <li><a href="http://ibcbh.com.br/Palavra/Default.aspx?IdCanal=8&IdArea=8">Palavra</a></li>
              </ul>
            </div>
          </div>
        </div><!-- /.navbar -->
      </div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Sistema de Células</h1>
        <p class="lead">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
        <a class="btn btn-large btn-success" href="/auth/login">Entrar</a>
      </div>

      <hr>

      <!-- Example row of columns -->
      <div class="row-fluid">
        <div class="span4">
          <h2>Notícia 1</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">veja mais &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Notícia 2</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn" href="#">veja mais &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Notícia 3</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
          <p><a class="btn" href="#">veja mais &raquo;</a></p>
        </div>
      </div>

      <hr>