<div class="masthead">
        <h3 class="muted">Igreja Batista Central</h3>
        <div class="navbar">
          <div class="navbar-inner">
            <div class="container">
              <ul class="nav">
                <li class="active"><a href="#">Células</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=3&IdArea=3">A Igreja</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=4&IdArea=4">Células</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=5&IdArea=5">Ministérios</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=7&IdArea=7">CCM</a></li>
                <li><a href="http://ibcbh.com.br/Conteudos/Default.aspx?IdCanal=6&IdArea=6">Missões</a></li>
                <li><a href="http://ibcbh.com.br/Palavra/Default.aspx?IdCanal=8&IdArea=8">Palavra</a></li>
              </ul>
            </div>
          </div>
        </div><!-- /.navbar -->
      </div>

      <!-- Jumbotron -->
      <div class="jumbotron">
        <h1>Sistema de Células</h1>
        <p class="lead">Um sistema de células totalmente novo para você líder da Igreja Batista Central. (podemos colocar outros textos aqui).</p>
        <a class="btn btn-large btn-success" href="/auth/login">Entrar</a>
      </div>

      <hr>

      <!-- Example row of columns -->
      <div class="row-fluid">
        <div class="span4">
          <h2>Dia da Visão</h2>
          <p>A Central de Adoradores está de portas abertas para aqueles que tem interesse em servir nas áreas de: louvor (instrumental e canto), teatro, dança, audiovisual e coral. </p>
          <p><a class="btn" href="http://ibcbh.com.br/Conteudos/Detalhes.aspx?idcanal=2&idmateria=635">veja mais &raquo;</a></p>
        </div>
        <div class="span4">
          <h2>Revitalização de Igrejas</h2>
          <p>Pela graça de Deus a Central tem recebido inúmeros testemunhos de pastores que tiveram uma virada em seus ministérios e como consequência milhares de pessoas têm sido alcançada. </p>
          <p><a class="btn" href="http://ibcbh.com.br/Conteudos/Detalhes.aspx?idcanal=2&idmateria=634">veja mais &raquo;</a></p>
       </div>
        <div class="span4">
          <h2>Resgate 2013 </h2>
          <p>Tempos difíceis, opressão, tribulação, prisões, vícios e tantos problemas que enfrentamos nos impedem de viver uma vida plena e de liberdade.</p>
          <p><a class="btn" href="http://ibcbh.com.br/Conteudos/Detalhes.aspx?idcanal=2&idmateria=632">veja mais &raquo;</a></p>
        </div>
      </div>

      <hr>