<div class="row-fluid">
    <form class="form-horizontal" method="post" name="registerCell" action="/celula/cadastro">
    <input type="hidden" id="cell_id" name="cell_id" value="<?=$this->cell_id?>" />
        <fieldset>
            <legend>Reuniões</legend>
            <div class="control-group">
                <label class="control-label" for="input01">Dia da semana</label>
                <div class="controls">
                    <select class="span2" name="" id="">
                        <option value="1">Segunda-feira</option>
                        <option value="2">Terça-feira</option>
                        <option value="3">Quarta-feira</option>
                        <option value="4">Quinta-feira</option>
                        <option value="5">Sexta-feira</option>
                        <option value="6">Sábado</option>
                    </select>
                </div><!--/.controls -->
            </div><!--/.control-group -->
            <div class="control-group">
                <label class="control-label" for="input01">Hora início</label>
                <div class="controls">
                    <input type="text" class="span1" id="input01" placeholder="hh:mm" value="">
                </div><!--/.controls -->
            </div><!--/.control-group -->
        </fieldset>
    </form>
</div><!--/.row-fluid -->

<fieldset><legend>Endereço</legend></fieldset>
<?=$this->cellProfileForm?>