<div class="row-fluid">
    <form class="form-horizontal" method="post" name="registerCell" action="/celula/cadastro">
    <input type="hidden" id="cell_id" name="cell_id" value="<?=$this->cell_id?>" />
        <fieldset>
            <legend>Reuniões</legend>
            <div class="control-group">
                <label class="control-label" for="input01">Dia da semana</label>
                <div class="controls">
                    <select class="span2" name="dayWeek" id="dayWeek">
                        <option value="2" <?if($this->cellDetailed->week_day_id == 2) echo 'selected="seleted"';?>>Segunda-feira</option>
                        <option value="3" <?if($this->cellDetailed->week_day_id == 3) echo 'selected="seleted"';?>>Terça-feira</option>
                        <option value="4" <?if($this->cellDetailed->week_day_id == 4) echo 'selected="seleted"';?>>Quarta-feira</option>
                        <option value="5" <?if($this->cellDetailed->week_day_id == 5) echo 'selected="seleted"';?>>Quinta-feira</option>
                        <option value="6" <?if($this->cellDetailed->week_day_id == 6) echo 'selected="seleted"';?>>Sexta-feira</option>
                        <option value="7" <?if($this->cellDetailed->week_day_id == 7) echo 'selected="seleted"';?>>Sábado</option>
                    </select>
                </div><!--/.controls -->
            </div><!--/.control-group -->
            <div class="control-group">
                <label class="control-label" for="input01">Hora início</label>
                <div class="controls">
                    <input type="text" class="span1" name="hourStart" placeholder="hh:mm" value="<?=substr($this->cellDetailed->hour_start, 0, -3);?>" maxlength="5">
                </div><!--/.controls -->
            </div><!--/.control-group -->
            <div class="form-actions"><button type="submit" class="btn btn-primary" id="submitbutton" name="submit">Salvar</button></div>
        </fieldset>
    </form>
</div><!--/.row-fluid -->

<fieldset><legend>Endereço</legend></fieldset>
<?=$this->cellProfileForm?>
