<div class="row-fluid">
    <div class="span8">
        <div class="row-fluid">
            <div class="span12">
                <div class="page-header">
                    <h1>Lançamento de frequência</h1>
                </div>                    
            </div>
        </div><!--/.row-fluid -->
            
        <div class="row-fluid">
            <div class="span12">
                <ul class="nav nav-tabs">
                    <li class="active">
                        <a href="#frequencia" data-toggle="tab">Célula</a>
                    </li>
                    <!--  <li><a href="#frequencia-cultos" data-toggle="tab">Cultos</a></li>-->
                </ul>

                <div class="tab-content">
                    <div class="tab-pane active" id="frequencia">
                        <div class="span12">
                            <table class="table table-bordered">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th class="th-left">Nome</th>
                                        <th>17-11</th>
                                        <th>24-11</th>
                                        <th>01-12</th>
                                        <th>08-12</th>
                                        <th>15-12</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td colspan="8">Membros IBC</td>
                                    </tr>
                                   	<? 
						            foreach($this->membersRows as $members)
						            {
					            	if($members->position != 3){
						            ?>
						            <tr>
						                <td><?=$members->role?></td>
                                        <td class="td-left"><?=$members->name." ".$members->surname?></td>
                                        <td class="frequencia">
                                          <i class="icon-ok frequencia-presente"></i>
                                        </td>
                                        <td class="frequencia">
                                          <i class="icon-ok frequencia-presente"></i>
                                        </td>
                                        <td class="frequencia">
                                          <i class="icon-ok frequencia-presente"></i>
                                        </td>
                                        <td class="frequencia">
                                          <i class="icon-ok frequencia-presente"></i>
                                        </td>
                                        <td></td>
						            </tr>
						            <?
					            	}
						            }
						            ?>
						            <tr>
                                      <td colspan="8">Visitantes</td>
                                    </tr>
						            <?
						            foreach($this->membersRows as $members)
						            {
					            	if($members->position == 3){
						           	?>
                                    <tr>
                                        <td>Visitante</td>
                                        <td class="td-left"><?=$members->name." ".$members->surname?></td>
                                        <td class="frequencia">
                                          <i class="icon-remove frequencia-ausente"></i>
                                        </td>
                                        <td class="frequencia">
                                          <i class="icon-ok frequencia-presente"></i>
                                        </td>
                                        <td class="frequencia">
                                          <i class="icon-ok frequencia-presente"></i>
                                        </td>
                                        <td class="frequencia">
                                          <i class="icon-remove frequencia-ausente"></i>
                                        </td>
                                        <td class="frequencia"></td>
                                    </tr>
                                    <?
					            	}
					            	}
						            ?>
                                </tbody>
                            </table>
                        </div><!--/.span12 -->
                    </div><!--/.tab-pane -->
                </div><!--/.tab-content -->
            </div><!--/.span12 -->
        </div><!--/.row-fluid -->
    </div><!--/span8 -->
    
    <div class="span4">
        <div class="page-header">
            <h1>5 Submetas</h1>
        </div>

        <div class="accordion" id="submetas">
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta1" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Data de multiplicação
                    </a>
                </div>
                <div id="submeta1" class="accordion-body collapse">
                    <div class="accordion-inner">
                        <div class="row-fluid">
                            <div class="span12">
                                Faltam <strong><?=$this->amountDays?></strong> dias ou <strong><?=$this->amountWeeks?></strong> semanas
                            </div>
                        </div>
                        
                        <div class="row-fluid">
                            <div class="span12">
                                <form action="">
                                    <div class="input-append">
                                        <span class="input-small uneditable-input">
                                            <?=$this->dateMultiplication?>
                                        </span><button class="btn"><i class="icon-pencil"></i></button>
                                    </div>
                                    
                                </form>
                            </div>
                        </div>

                        
                    </div>
                </div>
            </div><!--/.accordion-group -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta2" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Presença de Deus
                    </a>
                </div>
                <div id="submeta2" class="accordion-body collapse">
                    <div class="accordion-inner">
                        <input class="span12" type="range">
                    </div>
                </div>
            </div><!--/.accordion-group -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta3" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Novo Líder
                    </a>
                </div>
                <div id="submeta3" class="accordion-body collapse">
                    <div class="accordion-inner">
                    	<? foreach($this->membersRows as $members){
					       if($members->position == 5){ ?>
                        <div class="row-fluid">
                            <div class="span8">
                                <p><?=$members->name." ".$members->surname?></p>
                            </div>
                            <div class="span4">
                                <span class="avaliacao-star">
                                    <a href="">
                                        <i class="icon-star"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star-empty"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star-empty"></i>
                                    </a>
                                </span>
                            </div>
                        </div>
                        <?} }?>
                    </div>
                </div>
            </div><!--/.accordion-group -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta4" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Novos Participantes
                    </a>
                </div>
                <div id="submeta4" class="accordion-body collapse">
                    <div class="accordion-inner">
                        <div class="row-fluid">
                            <div class="span4">
                                <div class="row-fluid">
                                    <div class="span12">
                                        Atual
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span12">
                                        <strong><?=$this->actualParticipants?></strong>
                                    </div>
                                </div>
                                
                            </div><!--/.span4 -->
                            <div class="span4">
                                <div class="row-fluid">
                                    <div class="span12">
                                        Alvo
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span12">
                                        <strong><?=$this->goalParticipants?></strong>
                                    </div>
                                </div>
                                
                            </div><!--/.span4 -->
                            <div class="span4">
                                <div class="row-fluid">
                                    <div class="span12">
                                        Faltam
                                    </div>
                                </div>
                                <div class="row-fluid">
                                    <div class="span12">
                                        <strong><?if($this->goalParticipants>$this->actualParticipants) echo $this->goalParticipants-$this->actualParticipants; else echo 0;?></strong>
                                    </div>
                                </div>
                                
                            </div><!--/.span4 -->

                        </div>

                    </div>
                </div>
            </div><!--/.accordion-group -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta5" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Novo Anfitrião
                    </a>
                </div>
                <div id="submeta5" class="accordion-body collapse">
                    <div class="accordion-inner">
                        <div class="row-fluid">
                            <form action="">
                                <div class="input-append">
                                    <span class="input-large uneditable-input">
                                        João Paulo Santos
                                    </span><button class="btn"><i class="icon-pencil"></i></button>
                                </div>
                                
                            </form>
                        </div>
                        
                    </div>
                </div>
            </div><!--/.accordion-group -->
        </div><!--/.accordion -->
    </div><!--/span-->
</div><!--/.row-fluid -->

<div class="teste">
<span class="multi-toggle-group" data-multi-toggle="">
  <i class="icon-ok" class="multi-toggle"></i>
  <i class="icon-remove" class="multi-toggle"></i>
</span>
</div>