<div class="row-fluid">
    <div class="span8">
        <div class="row-fluid">
            <div class="span12">
                <div class="page-header">
                    <h1>Lançamento de frequência</h1>
                </div>                    
            </div>
        </div><!--/.row-fluid -->
            
        <div class="row-fluid">
            <?=$this->frequency?>
        </div><!--/.row-fluid -->
    </div><!--/span8 -->
    
    <div class="span4">
        <div class="page-header">
            <h1>5 Submetas</h1>
        </div>

        <div class="accordion" id="submetas">
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta1" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Data de multiplicação
                    </a>
                </div>
                <div id="submeta1" class="accordion-body in collapse">
                    <div class="accordion-inner">
                        <?=$this->dateMultiplication?>
                    </div>
                </div>
            </div><!--/.accordion-group -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta2" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Presença de Deus
                    </a>
                </div>
                <div id="submeta2" class="accordion-body in collapse">
                    <div class="accordion-inner">
                        <input class="span12" type="range">
                    </div>
                </div>
            </div><!--/.accordion-group -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta3" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Novo Líder
                    </a>
                </div>
                <div id="submeta3" class="accordion-body in collapse">
                    <div class="accordion-inner">
                        <?=$this->futureLeader?>
                    </div>
                </div>
            </div><!--/.accordion-group -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta4" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Novos Participantes
                    </a>
                </div>
                <div id="submeta4" class="accordion-body in collapse">
                    <div class="accordion-inner">
                        <?=$this->participants?>
                    </div>
                </div>
            </div><!--/.accordion-group -->
            <div class="accordion-group">
                <div class="accordion-heading">
                    <a href="#submeta3" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
                        Novo Anfitrião
                    </a>
                </div>
                <div id="submeta3" class="accordion-body in collapse">
                    <div class="accordion-inner">
                        <?=$this->futureHost?>
                    </div>
                </div>
            </div><!--/.accordion-group -->
        </div><!--/.accordion -->
    </div><!--/span-->
</div><!--/.row-fluid -->

<input type="hidden" value="<?=$this->cell_id?>" id="cell_id" />

<div class="modal hide" id="add_participante">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Salvar</h3>
    </div>
    <div class="modal-body">
        <?=$this->formNoteCell?>
    </div>
</div>