<script type="text/x-handlebars" data-template-name="application">
<div class="container-fluid">
  <div class="row-fluid">

  <div class="span8">
      <div class="row-fluid">
        <div class="span12">
          <div class="page-header">
            <h1>Lançamento de frequência</h1>
          </div>                    
        </div>
      </div><!--/.row-fluid -->
            
      <div class="row-fluid">
        <div class="span12">
          <ul class="nav nav-tabs">
            <li class="active">
              <a href="#frequencia" data-toggle="tab">Célula</a>
            </li>
            <!--  <li><a href="#frequencia-cultos" data-toggle="tab">Cultos</a></li>-->
          </ul>

          <div class="tab-content">
            <div class="tab-pane active" id="frequencia">
              <div class="span12">
              
              {{outlet frequencia}}

              {{outlet newParticipant}}
            </div><!--/.span12 -->
          </div><!--/.tab-pane -->
        </div><!--/.tab-content -->
      </div><!--/.span12 -->
    </div><!--/.row-fluid -->
  </div><!--/span8 -->

  {{outlet subgoals}}
</div><!--/.row-fluid -->

<hr>
    <footer>
        <p>OpenSource</p>
    </footer>
</div><!--/.fluid-container-->
</script>
    
<script type="text/x-handlebars" data-template-name="frequencia">
  
Selecionar reunião: 
{{view Ember.Select
  contentBinding="allMeetings"
  optionLabelPath="content.date"
  optionValuePath="content.date"
  valueBinding="lastSelectedMeeting"}}

{{#if salvo}}
  <a style="float: right;" class="btn btn-success disabled">Salvo</a>
{{else}}
  <a style="float: right;" {{action "salvarFrequencia"}} class="btn btn-success">Salvar</a>
{{/if}}

<table class="table table-bordered">
  <thead>
    <tr>
      <th></th>
      <th class="th-left">Nome</th>
      {{#each dateMeetings}}
        <th>{{date}}</th>
      {{/each}}
    </tr>
  </thead>
  
  <tbody>
    <tr>
      <td colspan="8">Membros IBC</td>
    </tr>
    {{#each members}}
      <tr>
        <td>{{funcao}}</td>
        <td>{{nome}}</td>
        {{#each dateMeetings}}
          <td>
            <input type="checkbox">
          </td>
        {{/each}}
      </tr>
    {{/each}}

    <tr>
      <td colspan="8">Visitantes</td>
    </tr>
    {{#each visitors}}
      <tr>
        <td>{{funcao}}</td>
        <td>{{nome}}</td>
        {{#each dateMeetings}}
          <td>
            <input type="checkbox">
          </td>
        {{/each}}
      </tr>
    {{/each}}
  </tbody>
</table>

</script>


<script type="text/x-handlebars" data-template-name="subgoals">
<div class="span4">
  <div class="page-header">
    <h1>5 Submetas</h1>
  </div>



  <div class="accordion" id="submetas">
    <div class="accordion-group">
      <div class="accordion-heading">
        <a {{action "closeSubgoal1"}} href="#submeta1" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">
          Data de multiplicação
        </a>
      </div>
      <div id="submeta1" class="accordion-body collapse">
        <div class="accordion-inner">
          <div class="row-fluid">
            <div class="span12">
              
              <p {{action "editSubgoal1"}} class="subgoal-text">
                {{multiplicationDate}}
              </p>

              <div class="edit-subgoal-1">

                {{view Ember.TextField  placeholder="dd/mm/aaaa" valueBinding="newMultiplicationDate"}}

              <a {{action "saveSubgoal1"}} class="btn btn-success">Salvar</a>
              <a {{action "closeSubgoal1"}}>
                <i class="icon-remove"></i>
              </a>
            </div><!-- /.edit-subgoal-1 -->


              
              <br>
              
              {{#if hasMultiplicationDate}}
                Faltam <strong>{{remainingDays}}</strong> dias ou <strong>{{remainingWeeks}}</strong> semanas
              {{/if}}
            </div>
          </div>
        </div>
      </div><!-- /.accordion-body -->
    </div><!--/.accordion-group -->
      
    <!-- SUBMETA: Presença de Deus -->
    <div class="accordion-group">
      <div class="accordion-heading">
        <a href="#submeta2" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">Presença de Deus</a>
      </div>
      
      <div id="submeta2" class="accordion-body collapse">
        <div class="accordion-inner">
          <input class="span12" type="range">
        </div>
      </div>
    </div><!--/.accordion-group -->

    <!-- SUBMETA: Novo líder -->
    <div class="accordion-group">
      <div class="accordion-heading">
        <a href="#submeta3" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">Novo Líder</a>
      </div>
      
      <div id="submeta3" class="accordion-body collapse">
        <div class="accordion-inner">
          <? foreach($this->membersRows as $members){
                           if($members->position == 5){ ?>
                        <div class="row-fluid">
                            <div class="span8">
                                <p><?=$members->name." ".$members->surname?></p>
                            </div>
                            <div class="span4">
                                <span class="avaliacao-star">
                                    <a href="">
                                        <i class="icon-star"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star-empty"></i>
                                    </a>
                                    <a href="">
                                        <i class="icon-star-empty"></i>
                                    </a>
                                </span>
                            </div>
                        </div>
                        <?} }?>
                    </div>
                </div>
    </div><!--/.accordion-group -->
    
    <!-- SUBMETA: Novos participantes -->
    <div class="accordion-group">
      <div class="accordion-heading">
        <a href="#submeta4" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">Novos Participantes</a>
      </div>
      
      <div id="submeta4" class="accordion-body collapse">
        <div class="accordion-inner">
          <div class="row-fluid">
            <div class="span4">
              <div class="row-fluid">
                <div class="span12">Atual</div>
              </div>
              
              <div class="row-fluid">
                <div class="span12"><strong><?=$this->actualParticipants?></strong></div>
              </div>
            </div><!--/.span4 -->
            
            <div class="span4">
              <div class="row-fluid">
                <div class="span12">Alvo</div>
              </div>
              
              <div class="row-fluid">
                <div class="span12"><strong><?=$this->goalParticipants?></strong></div>
              </div>                 
            </div><!--/.span4 -->
            
            <div class="span4">
              <div class="row-fluid">
                <div class="span12">Faltam</div>
              </div>
              
              <div class="row-fluid">
                <div class="span12"><strong><?if($this->goalParticipants>$this->actualParticipants) echo $this->goalParticipants-$this->actualParticipants; else echo 0;?></strong></div>
              </div>
            </div><!--/.span4 -->
          </div><!-- /.row-fluid -->
        </div><!-- /.accordion-inner -->
      </div><!-- /.accordion-body -->
    </div><!--/.accordion-group -->
    
    <!-- SUBMETA: Novo anfitrião -->
    <div class="accordion-group">
      <div class="accordion-heading">
        <a {{action "closeSubgoal5"}} href="#submeta5" class="accordion-toggle submetas-info" data-toggle="collapse" data-parent="#submetas">Novo Anfitrião</a>
      </div>
      
      <div id="submeta5" class="accordion-body collapse">
        <div class="accordion-inner">
          <div class="row-fluid">

            <p {{action "editSubgoal5"}} class="subgoal-text">
              {{newHost}}
            </p>
            <div class="edit-subgoal-5">
              {{view Ember.TextField valueBinding="newHostInput" placeholder="Nome do futuro anfitrião"}}

              <a {{action "saveSubgoal5"}} class="btn btn-success">Salvar</a>
              <a {{action "closeSubgoal5"}}>
                <i class="icon-remove"></i>
              </a>
            </div><!-- /.edit-subgoal-5 -->

          </div>
        </div><!-- /.accordion-inner -->
      </div><!-- /.accordion-body -->
    </div><!--/.accordion-group -->
  </div><!--/.accordion -->
</div><!--/span4 -->
</script>

<script type="text/x-handlebars" data-template-name="new-participant">

<div class="add-new-visitor-box">
  {{view Em.TextField valueBinding="name" placeholder="Nome do visitante"}}

  <div>
  <a {{action "saveNewVisitor"}} class="btn btn-success">Salvar</a>
  <a {{action "closeNewVisitor"}}>
    <i class="icon-remove"></i>
  </a>
  </div>
</div>


<p class="add-visitor" {{action "addNewVisitor"}}>
  <i class="icon-plus"></i>
  Adicionar visitante
</p>






</script>