<div class="row-fluid" style="margin-left: 20px;">
    <div class="span12">
        <div class="page-header">
            <h1>Participantes</h1>
        </div>
    </div>
</div><!--/.row-fluid -->
<div class="row-fluid" style="margin-left: 20px;">
    <div class="span12">
        <a class="btn btn-primary" href="#add_participante" data-toggle="modal">
            <i class="icon-plus"></i>
            Participante
        </a>
        <br /><br /><br />
    </div>
</div><!--/.row-fluid -->
<div class="row-fluid" style="margin-left: 20px;">
    <div class="span9">
        <table class="table table-striped table-bordered">
            <thead>
                <tr>
                    <th class="th-left">Nome</th>
                    <th>Função</th>
                    <th>Categoria</th>
                </tr>
            </thead>
            <tbody>
	            <? 
	            foreach($this->membersRows as $members)
	            {
	            ?>
	            <tr>
	            	<td class="td-left">
                        <a href="#participante<?=$members->user_id?>" data-toggle="modal">
                            <?=$members->name." ".$members->surname?>
                        </a>
                    </td>
                    <td><?=$members->role?></td>
                    <td><?if($members->type == 1)echo "Membro IBC"; else echo "Não membro";?></td>
	            </tr>
	            <?
	            }
	            ?>
            </tbody>
        </table>
    </div>
    
</div><!--/.row-fluid -->

<!-- MODAL ADICIONAR PARTICIPANTE -->
<div class="modal hide" id="add_participante">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Adicionar Participante</h3>
    </div>
    <div class="modal-body">
    	<?=$this->newParticipantForm?>
	</div>
</div>

<?foreach($this->participantesForm as $formul){?>
<div class="modal hide" id="participante<?=$formul->getUserId()?>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><?=$formul->getUserName()?></h3>
  </div>
  <div class="modal-body">
    <?=$formul?>
  </div>
</div>
<?}?>
