<div class="row-fluid" style="margin-left: 20px;">
    <div class="span12">
        <div class="page-header">
            <h1>Participantes</h1>
        </div>
    </div>
</div><!--/.row-fluid -->
<div class="row-fluid" style="margin-left: 20px;">
    <div class="span12">
        <a class="btn btn-primary" href="#add_participante" data-toggle="modal">
            <i class="icon-plus"></i>
            Participante
        </a>
        <br /><br /><br />
    </div>
</div><!--/.row-fluid -->
<div class="row-fluid" style="margin-left: 20px;">
    <div class="span9">
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th class="th-left">Nome</th>
                    <th>Função</th>
                    <th>Categoria</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
            </thead>
            <tbody>
	            <? 
	            foreach($this->membersRows as $members)
	            {
	            ?>
	            <tr>
	            	<td class="td-left">
                        <a href="#participante<?=$members->user_id?>" data-toggle="modal">
                            <?=$members->name." ".$members->surname?>
                        </a>
                    </td>
                    <td><?=$members->role?></td>
                    <td><?if($members->type == 1)echo "Membro IBC"; else echo "Não membro";?></td>
                    <td><?if ($members->role != 'Lider'){?><a style='color: #000' href="#remove_participante<?=$members->user_id?>" data-toggle="modal"><i class="icon-trash"></i></a>
                        <?}?></td>
                    <td><i class="icon-envelope"></i></a></td>
	            </tr>
	            <?
	            }
	            ?>
            </tbody>
        </table>
    </div>
    
</div><!--/.row-fluid -->

<!-- MODAL ADICIONAR PARTICIPANTE -->
<div class="modal hide" id="add_participante">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>Adicionar Participante</h3>
        <div style='text-align: right;'>
            <input type="submit" name="submit" id="submitbuttonNewParticipant" value="Salvar" class="btn btn-success disable" disabled="disabled">
        </div>
    </div>
    <div class="modal-body">
    	<?=$this->newParticipantForm?>
	</div>
</div>

<?foreach($this->participantesForm as $formul){?>
<div class="modal hide" id="participante<?=$formul->getUserId()?>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3><?=$formul->getUserName()?></h3>
    <div style='text-align: right;'>
        <input onclick='editMember(<?=$formul->getUserId()?>);' type="submit" name="submit" id="submitbutton" value="Salvar" class="btn btn-success">
    </div>
  </div>
  <div class="modal-body">
    <?=$formul?>
  </div>
</div>
<?}?>

<?foreach($this->participantesForm as $formul){?>
<div class="modal hide" id="remove_participante<?=$formul->getUserId()?>">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Remover Participante</h3>
  </div>
  <div class="modal-body">
        Deseja remover da sua célula o participante <?=$formul->getUserName()?>?
  </div>
  <div class="modal-footer">
    <a href="#" onclick="removeParticipant(<?=$formul->getUserId()?>)" class="btn btn-danger">Remover</a>
  </div>
</div>
<?}?>