<!DOCTYPE html>
<!--
                                                                             
                                           lllllll                   lllllll 
                                           l:::::l                   l:::::l 
                                           l:::::l                   l:::::l 
                                           l:::::l                   l:::::l 
        cccccccccccccccc    eeeeeeeeeeee    l::::l uuuuuu    uuuuuu   l::::l   aaaaaaaaaaaaa   
      cc:::::::::::::::c  ee::::::::::::ee  l::::l u::::u    u::::u   l::::l   a::::::::::::a  
     c:::::::::::::::::c e::::::eeeee:::::eel::::l u::::u    u::::u   l::::l   aaaaaaaaa:::::a 
    c:::::::cccccc:::::ce::::::e     e:::::el::::l u::::u    u::::u   l::::l            a::::a 
    c::::::c     ccccccce:::::::eeeee::::::el::::l u::::u    u::::u   l::::l     aaaaaaa:::::a 
    c:::::c             e:::::::::::::::::e l::::l u::::u    u::::u   l::::l   aa::::::::::::a 
    c:::::c             e::::::eeeeeeeeeee  l::::l u::::u    u::::u   l::::l  a::::aaaa::::::a 
    c::::::c     ccccccce:::::::e           l::::l u:::::uuuu:::::u   l::::l a::::a    a:::::a 
    c:::::::cccccc:::::ce::::::::e         l::::::lu:::::::::::::::uul::::::la::::a    a:::::a 
     c:::::::::::::::::c e::::::::eeeeeeee l::::::l u:::::::::::::::ul::::::la:::::aaaa::::::a 
      cc:::::::::::::::c  ee:::::::::::::e l::::::l  uu::::::::uu:::ul::::::l a::::::::::aa:::a
        cccccccccccccccc    eeeeeeeeeeeeee llllllll    uuuuuuuu  uuuullllllll  aaaaaaaaaa  aaaa
                                                                             
    by @fabriciotav
-->

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="pt-BR"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="pt-BR"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="pt-BR"> <![endif]-->
<!-- Consider adding a manifest.appcache: h5bp.com/d/Offline -->
<!--[if gt IE 8]><!--> <html class="no-js" lang="pt-BR"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">

        <!-- Use the .htaccess and remove these lines to avoid edge case issues.
        More info: h5bp.com/i/378 -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

        <title>Célula</title>
        <meta name="description" content="Sistema de células para igrejas em células">

        <!-- Mobile viewport optimized: h5bp.com/viewport -->
        <meta name="viewport" content="width=device-width">

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons -->

  
        <link rel="stylesheet" href="/css/libs/bootstrap/bootstrap.css">
        <link rel="stylesheet" href="/css/admin-panel.css">
        <link rel="stylesheet" href="/css/libs/bootstrap/bootstrap-responsive.css">

        <!-- More ideas for your <head> here: h5bp.com/d/head-Tips -->

        <!-- All JavaScript at the bottom, except this Modernizr build.
            Modernizr enables HTML5 elements & feature detects for optimal performance.
            Create your own custom Modernizr build: www.modernizr.com/download/ -->
        <script src="/js/libs/modernizr/modernizr-2.5.3.min.js"></script>

        <link rel="shortcut icon" href="/favicon.ico">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon-precomposed" href="/apple-touch-icon-57-precomposed.png">
    </head>
    <body>
  
        <?php echo $this->layout()->content; ?>
    
        <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.0/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="/js/libs/jquery/jquery-1.8.0.min.js"><\/script>')</script>
    
        <script src="/js/libs/handlebars/handlebars-1.0.0.beta.6.js" type="text/javascript"></script>
    
        <script src="/js/libs/bootstrap/bootstrap.min.js"></script>
    
        <script src="/js/libs/ember/ember.js" type="text/javascript"></script>
        <script src="/js/libs/ember/ember-data.js" type="text/javascript"></script>
        <script src="/js/libs/d3/d3.v2.js" type="text/javascript"></script>
    
        <script src="/js/app.js"></script>


    </body>
</html>