<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Sistema de Células</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="/css/development/lib/bootstrap/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      
    </style>
    <link href="/css/development/lib/bootstrap/bootstrap-responsive.css" rel="stylesheet">
    <link href="/css/development/landing.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="../assets/js/html5shiv.js"></script>
    <![endif]-->

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="../assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
      <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
                    <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
                                   <link rel="shortcut icon" href="../assets/ico/favicon.png">
  </head>

  <body>

    <div class="container">
  
    <?php echo $this->layout()->content; ?>

    </div> <!-- /container -->
    
    <!-- Development -->
    <script src="/js/development/lib/jquery-1.8.3.js"></script>
    <script src="/js/development/lib/handlebars-1.0.rc.1.js"></script>
    <script src="/js/development/lib/bootstrap.min.js"></script>
    <script src="/js/development/lib/ember-1.0.0-pre.2.js"></script>
    <script src="/js/development/lib/d3.v2.js"></script>

    <script src="/js/development/site.js" type="text/javascript"></script>

    <!-- Production -->
    <!-- <script src="/js/landing.js"></script> -->
    <!-- <script src="https://s3.amazonaws.com/celula/js/landing.js"></script> -->
  </body>
</html>
