<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Célula</title>
    <meta name="description" content="Sistema de células para igrejas em células">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">
    <meta name="author" content="@fabriciotav & @andrehigher">

    <!-- Development -->
    <link rel="stylesheet" href="/css/development/lib/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="/css/development/lib/bootstrap/bootstrap-responsive.css">
    <link rel="stylesheet" href="/css/libs/jquery/ui-darkness/jquery-ui-1.9.2.custom.min.css">
    <link rel="stylesheet" href="/css/development/lib/font-awesome.css">
    <link rel="stylesheet" href="/css/development/app.css">
    
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/celula/frequencia">Igreja Batista Central</a>
            <div class="btn-group pull-right">
                <a class="btn btn-inverse dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-user"></i>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                <li>
                    <a href="/configuracoes/perfil">
                        <i class="icon-wrench"></i> Configurações
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="/auth/logout">
                        <i class="icon-signout"></i> Sair
                    </a>
                </li>
                </ul>
            </div>

            <div class="nav-collapse">
                <ul class="nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Célula
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/celula/frequencia">Frequência</a></li>
                            <li><a href="/celula/membros">Participantes</a></li>
                            <li><a href="/celula/cadastro">Cadastro</a></li>
                            <!-- <li><a href="/celula/perfil">Perfil</a></li> -->
                        </ul>
                    </li>
                    <? // Discipulador
                    $leaderNamespace = new Zend_Session_Namespace('leadership');
                    if(isset($leaderNamespace->position)){
                    if($leaderNamespace->position == 1) {?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Setor
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/setor/celulas">Células</a></li>
                        </ul>
                    </li>
                    <?} }?>
                    <? if(isset($leaderNamespace->position)){
                    if($leaderNamespace->position == 2) {?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Área
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/area/setores">Setores</a></li>
                        </ul>
                    </li>
                    <?} }?>
                    <? if(isset($leaderNamespace->position)){
                    if($leaderNamespace->position == 3) {?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Rede
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/rede/areas">Áreas</a></li>
                        </ul>
                    </li>
                    <?} }?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Recursos
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- <li><a {{action "gotoLessons" href="true"}}>Lições de Célula</a></li>
                            <li><a {{action "gotoPraise" href="true"}}>Louvor</a></li>
                            <li><a {{action "gotoDynamics" href="true"}}>Dinâmicas</a></li> -->
                            <li><a href="/recursos/licoes-de-celula">Lições de Célula</a></li>
                            <li><a href="/recursos/louvor">Louvor</a></li>
                            <li><a href="/recursos/dinamicas">Dinâmicas</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.conatiner-fluid -->
    </div>
</div><!--/.navbar -->

    <?php echo $this->layout()->content; ?>
    
    <script src="/js/development/lib/jquery-1.8.3.js"></script>
    <script src="/js/development/lib/bootstrap.min.js"></script>
    <script src="/js/libs/jquery/ui/jquery-ui-1.9.2.min.js"></script>
    <script src="/js/libs/jquery/jquery.maskedinput-1.3.min.js"></script>
    <script src="/js/development/lib/d3.v3.min.js"></script>
    <script src="/js/celula.js"></script>

  </body>
</html>
