<!DOCTYPE html>
<!--
                                                                             
                                           lllllll                   lllllll 
                                           l:::::l                   l:::::l 
                                           l:::::l                   l:::::l 
                                           l:::::l                   l:::::l 
        cccccccccccccccc    eeeeeeeeeeee    l::::l uuuuuu    uuuuuu   l::::l   aaaaaaaaaaaaa   
      cc:::::::::::::::c  ee::::::::::::ee  l::::l u::::u    u::::u   l::::l   a::::::::::::a  
     c:::::::::::::::::c e::::::eeeee:::::eel::::l u::::u    u::::u   l::::l   aaaaaaaaa:::::a 
    c:::::::cccccc:::::ce::::::e     e:::::el::::l u::::u    u::::u   l::::l            a::::a 
    c::::::c     ccccccce:::::::eeeee::::::el::::l u::::u    u::::u   l::::l     aaaaaaa:::::a 
    c:::::c             e:::::::::::::::::e l::::l u::::u    u::::u   l::::l   aa::::::::::::a 
    c:::::c             e::::::eeeeeeeeeee  l::::l u::::u    u::::u   l::::l  a::::aaaa::::::a 
    c::::::c     ccccccce:::::::e           l::::l u:::::uuuu:::::u   l::::l a::::a    a:::::a 
    c:::::::cccccc:::::ce::::::::e         l::::::lu:::::::::::::::uul::::::la::::a    a:::::a 
     c:::::::::::::::::c e::::::::eeeeeeee l::::::l u:::::::::::::::ul::::::la:::::aaaa::::::a 
      cc:::::::::::::::c  ee:::::::::::::e l::::::l  uu::::::::uu:::ul::::::l a::::::::::aa:::a
        cccccccccccccccc    eeeeeeeeeeeeee llllllll    uuuuuuuu  uuuullllllll  aaaaaaaaaa  aaaa
                                                                             
    by @fabriciotav
-->

<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Célula</title>
    <meta name="description" content="Sistema de células para igrejas em células">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">
    <meta name="author" content="@fabriciotav & @andrehigher">


    <link rel="shortcut icon" href="https://s3.amazonaws.com/celula/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="https://s3.amazonaws.com/celula/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://s3.amazonaws.com/celula/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://s3.amazonaws.com/celula/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="https://s3.amazonaws.com/celula/ico/apple-touch-icon-57-precomposed.png">

    <!-- Development -->
    <link rel="stylesheet" href="/css/development/lib/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="/css/development/lib/bootstrap/bootstrap-responsive.css">
    <link rel="stylesheet" href="/css/development/lib/font-awesome.css">
    <link rel="stylesheet" href="/css/development/app.css">
    
    <!-- Production -->
    <!-- <link rel="stylesheet" type="text/css" href="https://s3.amazonaws.com/prizz/css/app.css"> -->
  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="/">Igreja Batista Central</a>
            <div class="btn-group pull-right">
                <a class="btn btn-inverse dropdown-toggle" data-toggle="dropdown" href="#">
                    <i class="icon-user"></i>
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                <li>
                    <!-- <a {{action "gotoSettings" href="true"}}>
                        <i class="icon-wrench"></i> Configurações
                    </a> -->
                    <a href="/configuracoes/perfil">
                        <i class="icon-wrench"></i> Configurações
                    </a>
                </li>
                <li class="divider"></li>
                <li>
                    <a href="/auth/logout">
                        <i class="icon-signout"></i> Sair
                    </a>
                </li>
                </ul>
            </div>

            <div class="nav-collapse">
                <ul class="nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Célula
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/celula/#/celula/frequencia">Frequência</a></li>
                            <li><a href="/celula/#/celula/participantes">Participantes</a></li>
                            <!-- <li><a {{action "gotoRegister" href="true"}}>Cadastro</a></li> -->
                            <li><a href="/celula/cadastro">Cadastro</a></li>
                            <li><a href="/celula/#/celula/perfil">Perfil</a></li>
                        </ul>
                    </li>
                    <!--
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Setor
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/setor/celulas">Células</a></li>
                            <li><a href="/setor/perfil">Perfil</a></li>
                        </ul>
                    </li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Área
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/area/setores">Setores</a></li>
                            <li><a href="/area/perfil">Perfil</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Rede
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/rede/areas">Áreas</a></li>
                            <li><a href="/rede/perfil">Perfil</a></li>
                        </ul>
                    </li>
                  -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Recursos
                            <b class="caret"></b>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- <li><a {{action "gotoLessons" href="true"}}>Lições de Célula</a></li>
                            <li><a {{action "gotoPraise" href="true"}}>Louvor</a></li>
                            <li><a {{action "gotoDynamics" href="true"}}>Dinâmicas</a></li> -->
                            <li><a href="/recursos/licoes-de-celula">Lições de Célula</a></li>
                            <li><a href="/recursos/louvor">Louvor</a></li>
                            <li><a href="/recursos/dinamicas">Dinâmicas</a></li>
                        </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
        </div><!--/.conatiner-fluid -->
    </div>
</div><!--/.navbar -->

    <?php echo $this->layout()->content; ?>
    
    <!-- Development -->
    <script src="/js/development/lib/jquery-1.8.3.js"></script>
    <!-- // <script src="/js/development/lib/handlebars-1.0.rc.1.js"></script> -->
    <script src="/js/development/lib/bootstrap.min.js"></script>
    <!-- // <script src="/js/development/lib/ember-1.0.0-pre.2.js"></script> -->
    <script src="/js/development/lib/d3.v2.js"></script>

    <!-- // <script src="/js/development/app.js" type="text/javascript"></script> -->

    <!-- Production -->
    <!-- <script src="/js/all.js"></script> -->
    <!-- <script src="https://s3.amazonaws.com/celula/js/all.js"></script> -->
  </body>
</html>
