<!DOCTYPE html>
<!--
                                                                             
                                           lllllll                   lllllll 
                                           l:::::l                   l:::::l 
                                           l:::::l                   l:::::l 
                                           l:::::l                   l:::::l 
        cccccccccccccccc    eeeeeeeeeeee    l::::l uuuuuu    uuuuuu   l::::l   aaaaaaaaaaaaa   
      cc:::::::::::::::c  ee::::::::::::ee  l::::l u::::u    u::::u   l::::l   a::::::::::::a  
     c:::::::::::::::::c e::::::eeeee:::::eel::::l u::::u    u::::u   l::::l   aaaaaaaaa:::::a 
    c:::::::cccccc:::::ce::::::e     e:::::el::::l u::::u    u::::u   l::::l            a::::a 
    c::::::c     ccccccce:::::::eeeee::::::el::::l u::::u    u::::u   l::::l     aaaaaaa:::::a 
    c:::::c             e:::::::::::::::::e l::::l u::::u    u::::u   l::::l   aa::::::::::::a 
    c:::::c             e::::::eeeeeeeeeee  l::::l u::::u    u::::u   l::::l  a::::aaaa::::::a 
    c::::::c     ccccccce:::::::e           l::::l u:::::uuuu:::::u   l::::l a::::a    a:::::a 
    c:::::::cccccc:::::ce::::::::e         l::::::lu:::::::::::::::uul::::::la::::a    a:::::a 
     c:::::::::::::::::c e::::::::eeeeeeee l::::::l u:::::::::::::::ul::::::la:::::aaaa::::::a 
      cc:::::::::::::::c  ee:::::::::::::e l::::::l  uu::::::::uu:::ul::::::l a::::::::::aa:::a
        cccccccccccccccc    eeeeeeeeeeeeee llllllll    uuuuuuuu  uuuullllllll  aaaaaaaaaa  aaaa
                                                                             
    by @fabriciotav
-->

<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <title>Célula</title>
    <meta name="description" content="Sistema de células para igrejas em células">

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width">
    <meta name="author" content="@fabriciotav & @andrehigher">


    <link rel="shortcut icon" href="https://s3.amazonaws.com/celula/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="https://s3.amazonaws.com/celula/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="https://s3.amazonaws.com/celula/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="https://s3.amazonaws.com/celula/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="https://s3.amazonaws.com/celula/ico/apple-touch-icon-57-precomposed.png">

    <!-- Development -->
    <link rel="stylesheet" href="/css/development/lib/bootstrap/bootstrap.css">
    <link rel="stylesheet" href="/css/development/lib/bootstrap/bootstrap-responsive.css">
    <link rel="stylesheet" href="/css/development/lib/font-awesome.css">
    <link rel="stylesheet" href="/css/development/app.css">
    
    <!-- Production -->
    <!-- <link rel="stylesheet" type="text/css" href="https://s3.amazonaws.com/prizz/css/app.css"> -->
  </head>
  <body>
  
    <?php echo $this->layout()->content; ?>
    
    <!-- Development -->
    <script src="/js/development/lib/jquery-1.8.3.js"></script>

    <script src="/js/development/app.js" type="text/javascript"></script>

    <!-- Production -->
    <!-- <script src="/js/all.js"></script> -->
    <!-- <script src="https://s3.amazonaws.com/celula/js/all.js"></script> -->
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36929713-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

  </script>
  </body>
</html>
