<div class="row-fluid">
    <form class="form-horizontal" method="post" name="registerCell" action="/celula/cadastro">
		<fieldset>
			<legend>Editar Membro</legend>
				<div class="control-group">
					<label class="control-label" for="input01">Nome</label>
					<div class="controls">
						<input type="text" class="input-xlarge" id="name" name="name" placeholder="digite aqui o nome do membro">
						<input type="hidden" id="idmember" name="idmember">
					</div><!--/.controls -->
				</div><!--/.control-group -->
				<div class="control-group">
					<label class="control-label" for="input01">Supervisor</label>
					<div class="controls">
						<input type="text" class="input-xlarge" id="root_name" name="root_name" placeholder="digite aqui o nome do supervisor">
						<input type="hidden" id="root_idmember" name="root_idmember">
					</div><!--/.controls -->
				</div><!--/.control-group -->
		</fieldset>
		<div class="form-actions">
			<button type="submit" class="btn btn-primary">Adicionar Líder ao Sistema</button>
		</div>
	</form>
</div>