<div class="row-fluid">
    <form class="form-horizontal" method="post" name="registerCell" action="/celula/cadastro">
	<fieldset>
		<legend>Dados Gerais</legend>
			<div class="control-group">
				<label class="control-label" for="input01">Nome da igreja</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="address" name="address" value="<?=$this->address?>">
				</div><!--/.controls -->
			</div><!--/.control-group -->
			<div class="control-group">
				<label class="control-label" for="input01">Abreviação (aparecerá no sistema)</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="address" name="address" value="<?=$this->address?>">
				</div><!--/.controls -->
			</div><!--/.control-group -->
	</fieldset>
	<fieldset>
	            <legend>Endereço</legend>
	            <div class="control-group">
	                <label class="control-label" for="input01">Endereço</label>
	                <div class="controls">
	                    <input type="text" class="input-xlarge" id="address" name="address" value="<?=$this->address?>">
	                </div><!--/.controls -->
	            </div><!--/.control-group -->
	            <div class="control-group">
	                <label class="control-label" for="input01">Número</label>
	                <div class="controls">
	                    <input type="text" class="input-xlarge" id="number" name="number" value="<?=$this->number?>">
	                </div><!--/.controls -->
	            </div><!--/.control-group -->
	            <div class="control-group">
	                <label class="control-label" for="input01">Complemento</label>
	                <div class="controls">
	                    <input type="text" class="input-xlarge" id="apartament" name="apartament" value="<?=$this->apartament?>">
	                </div><!--/.controls -->
	            </div><!--/.control-group -->
	            <div class="control-group">
	                <label class="control-label" for="input01">Bairro</label>
	                <div class="controls">
	                    <input type="text" class="input-xlarge" id="district" name="district" value="<?=$this->district?>">
	                </div><!--/.controls -->
	            </div><!--/.control-group -->
	            <div class="control-group">
	                <label class="control-label" for="input01">Município</label>
	                <div class="controls">
	                    <select class="" name="city" id="city">
	                        <option value="0">Belo Horizonte</option>
	                        <option value="0">Contagem</option>
	                        <option value="0">Nova Lima</option>
	                        <option value="0">Betim</option>
	                    </select>
	                </div><!--/.controls -->
	            </div><!--/.control-group -->
	            <div class="control-group">
	                <label class="control-label" for="input01">CEP</label>
	                <div class="controls">
	                    <input type="text" class="span2" id="zip_code" name="zip_code" placeholder="ex.: 30330-333"  value="<?=$this->zip_code?>">
	                </div><!--/.controls -->
	            </div><!--/.control-group -->
	        </fieldset>
	        
			<div class="form-actions">
				<button type="submit" class="btn btn-primary">Salvar alterações</button>
			</div>
		</form>
</div>