<div class="row-fluid">
    <form class="form-horizontal" method="post" name="registerCell" action="/celula/cadastro">
	<fieldset>
		<legend>Editar Membro</legend>
			<div class="control-group">
				<label class="control-label" for="input01">Nome</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="address" name="address" value="<?=$this->address?>">
				</div><!--/.controls -->
			</div><!--/.control-group -->
			<div class="control-group">
				<label class="control-label" for="input01">Sobrenome</label>
				<div class="controls">
					<input type="text" class="input-xlarge" id="address" name="address" value="<?=$this->address?>">
				</div><!--/.controls -->
			</div><!--/.control-group -->
	</fieldset>
			<div class="form-actions">
				<button type="submit" class="btn btn-primary">Salvar alterações</button>
			</div>
		</form>
</div>