<section class="access shadow">
  <div class="content">
    <h1 class="login-title">Administração</h1>
    <form action="/auth/login" method="post"><!-- precisa mudar a action -->
      <!-- <b>Mensagem de erro</b> -->
      <div class=""></div>
      <div class="field margin30">
        
        <input placeholder="Nome de usuário" id="login" name="login" size="30" title="Nome de usuário" type="text">
      </div>
      <div class="field margin20">
        
        <input placeholder="Senha" id="password" name="password" size="30" title="Senha" type="password">
      </div>
      <div class="field margin25">
        <input class="btn btn-primary btn-login" name="" type="submit" value="Entrar">
      </div>
    </form>
  </div>
  <div class="footer">
    <p class="center">
      <a href="/password/new">Esqueceu a senha?</a>
       · 
      <a href="/">Entrar como usuário</a>
    </p>
  </div>

</section>